In [1]:
# Data Analysis

import pandas as pd
import numpy as np

# Data Visualization 
import matplotlib.pyplot as plt
import seaborn as sns

## Array Functions

In [4]:
l1 = [[10,20,30],[40,50,60]]
l1

[[10, 20, 30], [40, 50, 60]]

In [6]:
arr1 = np.array(l1)
arr1

array([[10, 20, 30],
       [40, 50, 60]])

In [17]:
l2 = [[1,2,3],[4,5,6],[9,10,11]]
l2

[[1, 2, 3], [4, 5, 6], [9, 10, 11]]

In [18]:
arr2 = np.array(l2)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 11]])

## Method 1 : Creating a 2D array from a 1D array

In [23]:
arr3 = np.arange(10,26)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [24]:
arr4 = np.shape(arr3)
arr4

(16,)

In [28]:
arr4 = arr3.reshape(4,4)
arr4

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [29]:
arr4.ndim

2

## Method 2 : Creating a 2D array from a 1D array

In [48]:
arr5 = np.arange(1,17)
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [49]:
arr5.ndim

1

In [50]:
arr6 = np.resize([arr5],(4,4))
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [51]:
arr6.ndim

2

## Note: Reshape and Resize are used to coonvert 1D array to 2D array

## Method 1: Creating a 1D array from a 2D array

In [32]:
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [33]:
arr4 = arr3.reshape(4,4)
arr4

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [34]:
arr5= arr4.flatten()
arr5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [35]:
arr5.ndim

1

## Method 2 : Converting a 2D array into  1D array

In [39]:
arr5 = np.arange(10,26).reshape(4,4)
arr5

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [42]:
arr6=arr5.ravel()
arr6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

## Note: Flatten and Ravel functions are user for converting a 2D array into 1D array

## Swap Rows and Columns of a 2D array

In [53]:
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
arr6.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

## Concatinating the arrays

In [57]:
arr1

array([[10, 20, 30],
       [40, 50, 60]])

In [58]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 11]])

In [65]:
arr3 = np.concatenate([arr1,arr2], axis = 1)
arr3

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [67]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr2 = np.array([[9,8,7],[6,5,4]])
arr2

array([[9, 8, 7],
       [6, 5, 4]])

In [71]:
arr3 = np.concatenate([arr1,arr2])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7],
       [6, 5, 4]])

In [77]:
arr4 = np.concatenate([arr1,arr2],axis=1)
arr4

array([[1, 2, 3, 9, 8, 7],
       [4, 5, 6, 6, 5, 4]])

## Splitting the array 

In [73]:
arr4 = np.array([1,2,3,4,5,6,7,8,9])
arr4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
arr5 = np.split(arr4 ,3) # 3 different arrays
arr5

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

## Concatinating using hstack and vstack

In [75]:
arr2

array([[9, 8, 7],
       [6, 5, 4]])

In [80]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
arr3 = np.vstack([arr1,arr2])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7],
       [6, 5, 4]])

In [84]:
arr4 = np.hstack([arr1,arr2])
arr4


array([[1, 2, 3, 9, 8, 7],
       [4, 5, 6, 6, 5, 4]])

## vsplit() and hsplit()

In [85]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7],
       [6, 5, 4]])

In [88]:
arr5 = np.vsplit(arr4 , 2)
arr5

[array([[1, 2, 3, 9, 8, 7]]), array([[4, 5, 6, 6, 5, 4]])]

In [89]:
arr4

array([[1, 2, 3, 9, 8, 7],
       [4, 5, 6, 6, 5, 4]])

In [93]:
arr6 = np.hsplit(arr4, 3)
arr6

[array([[1, 2],
        [4, 5]]),
 array([[3, 9],
        [6, 6]]),
 array([[8, 7],
        [5, 4]])]

## Indexing and Slicing a 2D array

In [95]:
arr1 = np.arange(10,22).reshape(4,3)
arr1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [96]:
arr1[1,1]

14

In [101]:
arr1[1:3,1:3]

array([[14, 15],
       [17, 18]])

In [102]:
arr1[2:4,:2]

array([[16, 17],
       [19, 20]])

In [103]:
arr1[:2,1:3]

array([[11, 12],
       [14, 15]])

In [106]:
arr1[: , 1:]

array([[11, 12],
       [14, 15],
       [17, 18],
       [20, 21]])

In [107]:
arr1[2: , :]

array([[16, 17, 18],
       [19, 20, 21]])