In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### 1. Create a null vector of size 10 but the fifth value which is 1.


In [4]:
null_vector = np.zeros([10])
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 2. Create a vector with values ranging from 10 to 49.


In [6]:
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 3. Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
arr1 = np.arange(0,9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
arr = np.array([1, 2, 0, 0, 4, 0])
arr1 = np.nonzero(arr)
arr1

(array([0, 1, 4], dtype=int64),)

### 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [18]:
import random
arr2 = np.random.randint(100,1000,100)
arr2

array([593, 320, 500, 288, 745, 836, 333, 372, 198, 423, 393, 704, 590,
       897, 942, 864, 202, 802, 929, 698, 400, 903, 819, 539, 434, 528,
       427, 630, 370, 664, 737, 380, 580, 528, 631, 636, 100, 114, 272,
       635, 210, 907, 864, 523, 740, 390, 597, 317, 321, 453, 826, 553,
       847, 914, 914, 888, 820, 992, 263, 325, 874, 886, 501, 200, 129,
       151, 841, 566, 905, 843, 183, 247, 622, 601, 929, 610, 132, 703,
       202, 140, 244, 469, 324, 587, 625, 191, 496, 900, 895, 278, 868,
       801, 404, 437, 770, 691, 842, 559, 433, 515])

In [19]:
arr2.reshape(10,10)

array([[593, 320, 500, 288, 745, 836, 333, 372, 198, 423],
       [393, 704, 590, 897, 942, 864, 202, 802, 929, 698],
       [400, 903, 819, 539, 434, 528, 427, 630, 370, 664],
       [737, 380, 580, 528, 631, 636, 100, 114, 272, 635],
       [210, 907, 864, 523, 740, 390, 597, 317, 321, 453],
       [826, 553, 847, 914, 914, 888, 820, 992, 263, 325],
       [874, 886, 501, 200, 129, 151, 841, 566, 905, 843],
       [183, 247, 622, 601, 929, 610, 132, 703, 202, 140],
       [244, 469, 324, 587, 625, 191, 496, 900, 895, 278],
       [868, 801, 404, 437, 770, 691, 842, 559, 433, 515]])

In [22]:
print(max(arr2))
print(min(arr2))

992
100


In [23]:
type(arr2)

numpy.ndarray