In [4]:
## Data Analysis libraries

import pandas as pd
import numpy as np

## Data visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
!pip install numpy

## What is NumPy?

- It is a scientific libraru used to numerical operations. (Numerical - Num, python - py, i.e. NumPy
- The main data structure of NumPy is Arrays.
- It is the foundation library used for python programming specifically for machine learning.
- Pandas and SciPy are the advanced libraries which are built on NumPy.

### Creating NumPy Array

In [1]:
li = [10,20,30,40,50,60]
li

[10, 20, 30, 40, 50, 60]

In [6]:
## Create a numpy from the above list

arr = np.array(li)
arr

array([10, 20, 30, 40, 50, 60])

In [7]:
## check whether arr is a numpy array


type(arr)

numpy.ndarray

- ndarray means n - dimensional array

In [8]:
li = [10,20,30,40.5,50.5,60]
li

[10, 20, 30, 40.5, 50.5, 60]

In [9]:
arr = np.array(li)
arr

array([10. , 20. , 30. , 40.5, 50.5, 60. ])

In [14]:
l2 = [10,20,30,'Akshay']
l2

[10, 20, 30, 'Akshay']

In [15]:
arr = np.array(l2)
arr

array(['10', '20', '30', 'Akshay'], dtype='<U11')

- Note: Array is a homogeneous data structure. Inside the array data must be of same data type.

## Addition and Multiplication Operations on lists and NumPy arrays

In [16]:
l1 = [10,20,30,40]
l1

[10, 20, 30, 40]

In [17]:
l2 = [50,60,70,80]
l2

[50, 60, 70, 80]

In [18]:
l1 + l2

[10, 20, 30, 40, 50, 60, 70, 80]

- Plus Operation on a list is concatination

In [21]:
arr1 = np.array([10,20,30,40])
arr1

array([10, 20, 30, 40])

In [22]:
arr2 = np.array([50,60,70,80])
arr2

array([50, 60, 70, 80])

In [23]:
arr1 + arr2

array([ 60,  80, 100, 120])

- Plus Operation will add the data inside the array element wise


### Note: The Number of elements must be same in both the arrays else you get value error as in the below example

In [24]:
arr3 = np.array([10,20,30])
arr4 = np.array([40,50,60,70])

arr3 + arr4

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

### Multiplication Operation on list and arrays

In [26]:
l1

[10, 20, 30, 40]

In [28]:
l1 * 3

[10, 20, 30, 40, 10, 20, 30, 40, 10, 20, 30, 40]

- Multiplication Operation on lists is a repitition operation

In [35]:
arr = np.array(l1)
arr

array([10, 20, 30, 40])

In [36]:
arr * 3

array([ 30,  60,  90, 120])

- Multiplication operation on an array will perform the multiplication

### Division and subtraction operation on lists and arrays
- division and subtraction cannot be performed on lists

In [38]:
l1

[10, 20, 30, 40]

In [39]:
l2

[50, 60, 70, 80]

In [43]:
 ## l1 /l2  Division not possible on a list
## l2 - l1  subtraction not possible on a list

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [44]:
arr1

array([10, 20, 30, 40])

In [45]:
arr1/2

array([ 5., 10., 15., 20.])

In [46]:
arr1//2

array([ 5, 10, 15, 20], dtype=int32)

In [52]:
arr5 = np.array([10,20,30,40])
arr6 = np.array([80,70,60,50])
arr5

array([10, 20, 30, 40])

In [53]:
arr6

array([80, 70, 60, 50])

In [54]:
arr6 - arr5

array([70, 50, 30, 10])

## Array Indexing

In [55]:
arr = np.array([10,20,30,40,50,60])
arr

array([10, 20, 30, 40, 50, 60])

In [60]:
arr[5]

60

In [61]:
arr[-3]

40

## Array Slicing

In [58]:
## Display [30,40,50] as output

arr[2:5]

array([30, 40, 50])

In [59]:

arr[0:6:2]

array([10, 30, 50])

### Array Indexing
- array_name[start__index: end_index:step_index]

- Note: start_index will be considered, end_index will not considered, step_index is used to add to the start_index

## Special Arrays Creation functions

In [62]:
zeros = np.zeros(4)
zeros

array([0., 0., 0., 0.])

In [63]:
z1 = np.zeros(10)
z1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [64]:
z2 = np.zeros((3,4))
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
## 1-dimensional Array
o1 = np.ones(4)
o1

array([1., 1., 1., 1.])

In [67]:
o2 = np.ones((3,4))
o2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
o3 = np.ones((3,4,2))
o3

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [70]:
## 2-Dimensional array
o4 = np.ones((3,4))
o4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
## 3-Dimensional Array
o4 = np.ones((3,4,5))
o4

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [74]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [75]:
arr1 = np.arange(10,25)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [76]:
arr1 = np.arange(10,50,5)
arr1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [79]:
arr1 = np.linspace(10,50,5)
arr1

array([10., 20., 30., 40., 50.])

- linspace is used to create an array with equal spacing between any two values of the array


In [92]:
np.full(5, 'Akshay')

array(['Akshay', 'Akshay', 'Akshay', 'Akshay', 'Akshay'], dtype='<U6')

In [93]:
np.full((3,2), 'Akshay')

array([['Akshay', 'Akshay'],
       ['Akshay', 'Akshay'],
       ['Akshay', 'Akshay']], dtype='<U6')

### Arithemetic operations on array
- Addition (+)
- Multiplication (*)
- Division (/)
- int division( // )
- subtraction (-)

- For example refer above cells where we discussed difference between lists and Arrays

## Statistical operations on an Array

In [80]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [81]:
np.mean(arr)

14.5

In [82]:
np.median(arr)

14.5

In [84]:
np.std(arr)  ## Standard deviation

2.8722813232690143

In [85]:
np.var(arr) ## var stands for variance

8.25

In [87]:
arr.shape ## it is used for counting the total values present in an array

(10,)

In [88]:
z = np.zeros(6)
z

array([0., 0., 0., 0., 0., 0.])

In [89]:
z.ndim

1

In [90]:
z1 = np.zeros((3,4,2))
z1

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [91]:
z1.ndim

3

## Boolean Indexing (Conditional Indexing)

In [94]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [95]:
arr > 14

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [96]:
arr[arr > 14]

array([15, 16, 17, 18, 19])

In [98]:
arr6 = np.array([12,54,23,65,43,68,43,87,54,245,8543,35,8765])
arr6

array([  12,   54,   23,   65,   43,   68,   43,   87,   54,  245, 8543,
         35, 8765])

In [101]:
arr6[arr6 > 50]

array([  54,   65,   68,   87,   54,  245, 8543, 8765])

In [107]:
arr6[(arr6 > 50) & (arr6< 100)]

array([54, 65, 68, 87, 54])

In [108]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [109]:
arr[(arr%3==0) & (arr%5==0)]

array([15])

In [110]:
arr[(arr%3==0) | (arr%5==0)]

array([10, 12, 15, 18])