In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
arr1 = np.array([[0,1],[2,3]])
arr1

array([[0, 1],
       [2, 3]])

In [4]:
np.max(arr1)

3

In [5]:
np.min(arr1)

0

In [10]:
flat_arr = arr1.flatten()
flat_arr

array([0, 1, 2, 3])

In [12]:
print('Index of max value',np.argmax(flat_arr))
print('Index of min value',np.argmin(flat_arr))

Index of max value 3
Index of min value 0


## find the sum of the below array

In [14]:
arr2 = np.arange(10,19)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [19]:
arr3 = arr2.reshape(3,3)
arr3

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [20]:
print(np.sum(arr3))

126


In [21]:
print(sum(arr3))

[39 42 45]


In [26]:
np.sum(arr3,axis=1)

array([33, 42, 51])

In [27]:
arr3

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [36]:
arr = np.arange(50,66).reshape(4,4)
arr

array([[50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61],
       [62, 63, 64, 65]])

In [38]:
np.mean(arr,axis = 0)

array([56., 57., 58., 59.])

In [39]:
np.mean(arr,axis = 1)

array([51.5, 55.5, 59.5, 63.5])

In [40]:
np.median(arr,axis = 0)

array([56., 57., 58., 59.])

In [41]:
np.median(arr,axis = 1)

array([51.5, 55.5, 59.5, 63.5])

In [42]:
np.std(arr,axis = 0)

array([4.47213595, 4.47213595, 4.47213595, 4.47213595])

In [43]:
np.std(arr,axis = 1)

array([1.11803399, 1.11803399, 1.11803399, 1.11803399])

In [44]:
np.var(arr,axis = 0)

array([20., 20., 20., 20.])

In [45]:
np.var(arr,axis = 1)

array([1.25, 1.25, 1.25, 1.25])

In [46]:
arr

array([[50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61],
       [62, 63, 64, 65]])

In [47]:
arr[1:,2:]

array([[56, 57],
       [60, 61],
       [64, 65]])

In [49]:
arr[1:3,:]

array([[54, 55, 56, 57],
       [58, 59, 60, 61]])

In [50]:
## rever the array

arr[:,::-1]

array([[53, 52, 51, 50],
       [57, 56, 55, 54],
       [61, 60, 59, 58],
       [65, 64, 63, 62]])

In [51]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [55]:
data =sns.load_dataset('penguins')
data

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            NaN     NaN  
4         3450.0  Female  
..           ...     ...  
339          NaN     NaN  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]

In [56]:
data.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [57]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [58]:
data['sex'].value_counts(normalize = True) * 100

Male      50.45045
Female    49.54955
Name: sex, dtype: float64

In [60]:
data['sex'].value_counts()

Male      168
Female    165
Name: sex, dtype: int64

In [61]:
data['species'].value_counts(normalize = True) * 100

Adelie       44.186047
Gentoo       36.046512
Chinstrap    19.767442
Name: species, dtype: float64

In [62]:
data['island'].value_counts(normalize = True) * 100

Biscoe       48.837209
Dream        36.046512
Torgersen    15.116279
Name: island, dtype: float64

In [63]:
#average body mass 
data['body_mass_g'].mean()

4201.754385964912

### Array Creaation function

In [64]:
arr = np.random.randint(25,50,10)
arr

array([43, 39, 48, 39, 37, 33, 33, 36, 27, 43])

In [66]:
np.sort(arr)

array([27, 33, 33, 36, 37, 39, 39, 43, 43, 48])

In [67]:
arr = np.random.randint(50,100,15).reshape(3,5)
arr

array([[95, 60, 95, 72, 60],
       [83, 70, 76, 50, 62],
       [52, 61, 60, 57, 77]])

In [68]:
np.sort(arr)

array([[60, 60, 72, 95, 95],
       [50, 62, 70, 76, 83],
       [52, 57, 60, 61, 77]])

In [69]:
## where

arr = np.random.randint(10,50,15)
arr

array([40, 42, 10, 27, 18, 28, 24, 17, 43, 42, 30, 37, 36, 24, 26])

In [71]:
np.where(arr % 5 != 0,arr,arr*10)

array([400,  42, 100,  27,  18,  28,  24,  17,  43,  42, 300,  37,  36,
        24,  26])